language: cpp

dist: trusty
sudo: true

os:
  - linux
  - osx

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu=sdk-team/ppa
  - sudo apt-get -qq update
  - sudo apt-get install qtbase5-dev qt5-qmake

script:
  - qmake -v
  - qmake
  - make
